from params import MAIN_PARAMS, AGENT_PARAMS, TANK_DIST

MAIN_PARAMS["RENDER"] = True
MAIN_PARAMS["LIVE_REWARD_PLOT"] = False

AGENT_PARAMS["EPSILON"] = [1]
AGENT_PARAMS["SAVE_MODEL"] = [False]
AGENT_PARAMS["LOAD_MODEL"] = [True]
AGENT_PARAMS["TRAIN_MODEL"] = [False]


TANK_DIST[0]["pre_def_dist"] = True
