from params import MAIN_PARAMS, AGENT_PARAMS

MAIN_PARAMS["RENDER"] = True
MAIN_PARAMS["LIVE_REWARD_PLOT"] = False

AGENT_PARAMS["EPSILON"] = 0
AGENT_PARAMS["SAVE_MODEL"] = False
AGENT_PARAMS["LOAD_MODEL"] = True
AGENT_PARAMS["TRAIN_MODEL"] = False
AGENT_PARAMS["MODEL_NAME"] = "Network_[10]HL"

